name: Compile and Upload Artifacts

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.1

    - name: Compile for Ubuntu x86-64
      run: |
        GOOS=linux GOARCH=amd64 go build -o nettest-linux-x86-64

    - name: Compile for Ubuntu arm64
      run: |
        GOOS=linux GOARCH=arm64 go build -o nettest-linux-arm64

    - name: Archive Linux Binaries
      run: |
        tar -czvf nettest-linux-binaries.tar.gz nettest-linux-x86-64 nettest-linux-arm64

    - name: Upload Linux Binaries
      uses: actions/upload-artifact@v2
      with:
        name: nettest-linux-binaries
        path: nettest-linux-binaries.tar.gz

  build-windows:
    name: Build Windows Binaries
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.1

    - name: Compile for Windows x86-64
      run: |
        set GOOS=windows
        set GOARCH=amd64
        go build -o nettest-windows-x86-64.exe

    - name: Compile for Windows arm64
      run: |
        set GOOS=windows
        set GOARCH=arm64
        go build -o nettest-windows-arm64.exe

    - name: Archive Windows Binaries
      run: |
        tar -czvf nettest-windows-binaries.tar.gz nettest-windows-x86-64.exe nettest-windows-arm64.exe

    - name: Upload Windows Binaries
      uses: actions/upload-artifact@v2
      with:
        name: nettest-windows-binaries
        path: nettest-windows-binaries.tar.gz
